version: '3.8'

services:
  fractional-mortgage-dapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
